version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: superalsrk/springboot-demo-session-with-redis
    volumes:
      - /tmp
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:3.2.6
    command: redis-server --requirepass redis


