version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: superalsrk/springboot-demo-basic-security
    volumes:
      - /tmp
    ports:
      - "9090:9090"


