version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: superalsrk/springboot-demo-websocket-simple
    volumes:
      - /tmp
    ports:
      - "8080:8080"
